
### CREATE PROCES SFIRST
POST http://localhost:3000/process
Content-Type: application/json

{
    "destination" : "destinations 22", 
    "location":"dest 2",
  "user":"example ako22" ,
  "cpnum":"911111122" ,
  "NoOfPassengers":6
}

###
POST http://localhost:3000/driver/populate

###
GET http://localhost:3000/process
###

###CHECK DRIVERS BEFORE 
GET http://localhost:3000/driver

### Check queue before
GET http://localhost:3000/queue
###
POST http://localhost:3000/queue/booking
Content-Type: application/json

{
    "processId": "61e2f576cea94101e5771fac"
}

###CHECK DRIVERS AFTER
GET http://localhost:3000/driver

### Check queue AFTER
GET http://localhost:3000/queue

### RETURN TO DRIVER LIST FROM QUEUE
POST http://localhost:3000/queue/booking-rejected
Content-Type: application/json

{
    "queueId": "61e2fed8cea94101e5771fe5"
}


# POST http://localhost:3000/queue/booking-cancelled
# Content-Type: application/json

# {
#     "queueId": "61b5d75f10cd45dbd7fffc1b"
# }

###
GET http://localhost:3000/queue/move-drivers-from-queue

###CHECK DRIVERS AFTER
DELETE  http://localhost:3000/driver

###
GET 